export const LOGIN_FETCH_REQUESTED = 'LOGIN_FETCH_REQUESTED';
export const LOGIN_FETCH_FAILED = 'LOGIN_FETCH_FAILED';
export const LOGIN_FETCH_SUCCEEDED = 'LOGIN_FETCH_SUCCEEDED';

export const LOGOUT_FETCH_REQUESTED = 'LOGOUT_FETCH_REQUESTED';
export const LOGOUT_FETCH_FAILED = 'LOGOUT_FETCH_FAILED';
export const LOGOUT_FETCH_SUCCEEDED = 'LOGOUT_FETCH_SUCCEEDED';
